<!DOCTYPE HTML>
<!--
	Editorial by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Visualización de Datos</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Main -->
					<div id="main">
						<div class="inner">

							<!-- Header -->
								<header id="header">
									<a href="index.html" class="logo"><strong>VISDAT</strong> Práctica HTML</a>
									<ul class="icons">
										<li><a href="https://twitter.com/mjaramar" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
										<li><a href="https://www.facebook.com/manjarmar" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
										<li><a href="https://www.instagram.com/jara.92/" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
									</ul>
								</header>

							<!-- Content -->
								<section>
									<header class="main">
										<h1>Resumen descriptivo</h1>
									</header>
									<p>A continuación se muestra un breve resumen descriptivo de todas las variables que componen nuestros datos:</p>
<pre class="r"><code>summary(cameras)</code></pre>
<pre><code>##                     Model       Release.date Max.resolution Low.resolution
##  Agfa ePhoto 1280      :   1   2007   :162   Min.   :   0   Min.   :   0  
##  Agfa ePhoto 1680      :   1   2006   :152   1st Qu.:2048   1st Qu.:1120  
##  Agfa ePhoto CL18      :   1   2005   :143   Median :2560   Median :2048  
##  Agfa ePhoto CL30      :   1   2004   :141   Mean   :2473   Mean   :1775  
##  Agfa ePhoto CL30 Clik!:   1   2003   :101   3rd Qu.:3072   3rd Qu.:2560  
##  Agfa ePhoto CL45      :   1   2002   : 89   Max.   :5616   Max.   :4992  
##  (Other)               :1030   (Other):248                                
##  Effective.pixels Zoom.wide..W.   Zoom.tele..T.   Normal.focus.range
##  Min.   : 0.00    Min.   : 0.00   Min.   :  0.0   Min.   :  0.00    
##  1st Qu.: 3.00    1st Qu.:35.00   1st Qu.: 96.0   1st Qu.: 30.00    
##  Median : 4.00    Median :36.00   Median :108.0   Median : 50.00    
##  Mean   : 4.59    Mean   :32.96   Mean   :121.5   Mean   : 44.13    
##  3rd Qu.: 7.00    3rd Qu.:38.00   3rd Qu.:117.0   3rd Qu.: 60.00    
##  Max.   :21.00    Max.   :52.00   Max.   :518.0   Max.   :120.00    
##                                                                     
##  Macro.focus.range Storage.included Weight..inc..batteries.
##  Min.   : 0.000    Min.   :  0.00   Min.   :   0.0         
##  1st Qu.: 3.000    1st Qu.:  8.00   1st Qu.: 180.0         
##  Median : 6.000    Median : 16.00   Median : 226.0         
##  Mean   : 7.786    Mean   : 17.45   Mean   : 319.3         
##  3rd Qu.:10.000    3rd Qu.: 20.00   3rd Qu.: 350.0         
##  Max.   :85.000    Max.   :450.00   Max.   :1860.0         
##                                                            
##    Dimensions        Price       
##  Min.   :  0.0   Min.   :  14.0  
##  1st Qu.: 92.0   1st Qu.: 149.0  
##  Median :101.0   Median : 199.0  
##  Mean   :105.4   Mean   : 457.9  
##  3rd Qu.:115.0   3rd Qu.: 399.0  
##  Max.   :240.0   Max.   :7999.0  
## </code></pre>
<pre class="r"><code>summary(cameras$Release.date)</code></pre>
<pre><code>##   1994   1995   1996   1997   1998   1999   2000   2001   2002   2003 
##      1      1      4     11     32     53     61     85     89    101 
##   2004   2005   2006   2007 DOUBLE 
##    141    143    152    162      0</code></pre>
<p>Algunos datos interesantes:</p>
<ul>
<li>La muestra recoge 1030 modelos diferentes de cámaras réflex y semiautomáticas.</li>
<li>Hay mayor cantidad de observaciones de modelos de cámaras actuales (162 modelos de 2007 versus 1 modelo de 1994). En cuanto a fecha de lanzamiento la muestra está desbalanceada.</li>
<li>El precio medio de los 1030 modelos del estudio ronda en torno a los 458 euros.</li>
<li>Los megapíxeles se mueven en un rango entre 0mpx y 21mpx, con una media de 5mpx.</li>
</ul>
<p>A continuación se muestran las 15 categorías en las que se divide la variable <strong>Release.date</strong> :</p>
<pre class="r"><code>levels(cameras$Release.date)</code></pre>
<pre><code>##  [1] &quot;1994&quot;   &quot;1995&quot;   &quot;1996&quot;   &quot;1997&quot;   &quot;1998&quot;   &quot;1999&quot;   &quot;2000&quot;  
##  [8] &quot;2001&quot;   &quot;2002&quot;   &quot;2003&quot;   &quot;2004&quot;   &quot;2005&quot;   &quot;2006&quot;   &quot;2007&quot;  
## [15] &quot;DOUBLE&quot;</code></pre>

								</section>
						</div>	
					</div>
					
					

				<!-- Sidebar -->
					<div id="sidebar">
						<div class="inner">

							<!-- Menu -->
							<div>
							</div>
								<nav id="menu">
									<header class="major">
										<h2>Menu</h2>
									</header>
									<ul>
										<li><a href="index.html">Página principal</a></li>
										<li><a href="datos.html">Datos</a></li>
										<li><a href="resumen.html">Resumen descriptivo</a></li>
										<li>
											<span class="opener">Análisis de variables</span>
											<ul>
												<li><a href="analisis.html#valores-atipicos">Valores atípicos</a></li>
												<li><a href="analisis.html#distribuciones">Distribución</a></li>
												<li><a href="analisis.html#graficosqq">Gráficos Q-Q</a></li>
											</ul>
										</li>
										<li>
											<span class="opener">Relaciones entre variables</span>
											<ul>
												<li><a href="relaciones.html#pixels-price">Effective.pixels vs Price</a></li>
												<li><a href="relaciones.html#max-min">Max.resolution vs Low.resolution</a></li>
												<li><a href="relaciones.html#normal-macro">Normal.focus.range vs Macro.focus.range</a></li>
											</ul>
										</li>
										<li><a href="conclusiones.html">Conclusiones</a></li>
									</ul>
								</nav>


							<!-- Section -->
								<section>
									<header class="major">
										<h2>Contacto</h2>
									</header>
									<ul class="contact">
										<li class="fa-envelope-o"><a href="#">jarabct@gmail.com</a></li>
									</ul>
								</section>

							<!-- Footer -->
								<footer id="footer">
									<p class="copyright">&copy; Untitled. All rights reserved. Demo Images: <a href="https://unsplash.com">Unsplash</a>. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
								</footer>

						</div>
					</div>

			</div>


		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>